version = 0.1
[default.deploy.parameters]
stack_name = "notion2github"
resolve_s3 = true
s3_prefix = "notion2github"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
