AWSTemplateFormatVersion: 2010-09-09
Description: >-
  notion-sam
# 필값
Transform:
  - AWS::Serverless-2016-10-31
Resources:
  blog:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/blog.Handler
      Runtime: nodejs18.x

      # 기본값
      Architectures:
        - x86_64
      MemorySize: 256
      Timeout: 200
      Description: Notion to GitHub
      Environment:
        Variables:
          NOTION_SECRET_API_KEY: "{{resolve:secretsmanager:Blog:SecretString:NOTION_SECRET_API_KEY}}"
          GITHUB_TOKEN: "{{resolve:secretsmanager:Blog:SecretString:GITHUB_TOKEN}}"

      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action: "secretsmanager:GetSecretValue"
              Resource:
                - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:Blog-mZB6i0"
                - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:googleAPI-XJYnW3"
      Events:
        Api:
          Type: Api
          Properties:
            # PATH = {pageid}/{blog repo}/{title}
            Path: /{pageid}/{title}
            Method: get

# 출력
Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
